/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ClinicSignupRouteImport } from './routes/clinic-signup'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as ReceptionistIndexRouteImport } from './routes/receptionist.index'
import { Route as PharmacistIndexRouteImport } from './routes/pharmacist.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperAdminFacilitiesRouteImport } from './routes/super-admin.facilities'
import { Route as SuperAdminAuditRouteImport } from './routes/super-admin.audit'
import { Route as ReceptionistRegistrationRouteImport } from './routes/receptionist.registration'
import { Route as ReceptionistQueueRouteImport } from './routes/receptionist.queue'
import { Route as ReceptionistProfilesRouteImport } from './routes/receptionist.profiles'
import { Route as ReceptionistAppointmentsRouteImport } from './routes/receptionist.appointments'
import { Route as PharmacistStockRouteImport } from './routes/pharmacist.stock'
import { Route as PharmacistDiagnosticsRouteImport } from './routes/pharmacist.diagnostics'
import { Route as PharmacistDeliveriesRouteImport } from './routes/pharmacist.deliveries'
import { Route as PharmacistAnalyticsRouteImport } from './routes/pharmacist.analytics'
import { Route as PatientPrivacyRouteImport } from './routes/patient.privacy'
import { Route as PatientMedicalRecordRouteImport } from './routes/patient.medical-record'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientAlertsRouteImport } from './routes/patient.alerts'
import { Route as NurseStockRouteImport } from './routes/nurse.stock'
import { Route as NursePatientsRouteImport } from './routes/nurse.patients'
import { Route as NurseDigitizeRouteImport } from './routes/nurse.digitize'
import { Route as NurseAppointmentsRouteImport } from './routes/nurse.appointments'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ReceptionistProfilesPidRouteImport } from './routes/receptionist.profiles_.$pid'
import { Route as NursePatientRecordPidRouteImport } from './routes/nurse.patient-record.$pid'
import { Route as DoctorPatientRecordPidRouteImport } from './routes/doctor.patient-record.$pid'

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicSignupRoute = ClinicSignupRouteImport.update({
  id: '/clinic-signup',
  path: '/clinic-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ReceptionistIndexRoute = ReceptionistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceptionistRoute,
} as any)
const PharmacistIndexRoute = PharmacistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacistRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperAdminFacilitiesRoute = SuperAdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAuditRoute = SuperAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ReceptionistRegistrationRoute =
  ReceptionistRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistQueueRoute = ReceptionistQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistProfilesRoute = ReceptionistProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistAppointmentsRoute =
  ReceptionistAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const PharmacistStockRoute = PharmacistStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => PharmacistRoute,
} as any)
const PharmacistDiagnosticsRoute = PharmacistDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => PharmacistRoute,
} as any)
const PharmacistDeliveriesRoute = PharmacistDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => PharmacistRoute,
} as any)
const PharmacistAnalyticsRoute = PharmacistAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PharmacistRoute,
} as any)
const PatientPrivacyRoute = PatientPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicalRecordRoute = PatientMedicalRecordRouteImport.update({
  id: '/medical-record',
  path: '/medical-record',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAlertsRoute = PatientAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => PatientRoute,
} as any)
const NurseStockRoute = NurseStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => NurseRoute,
} as any)
const NursePatientsRoute = NursePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => NurseRoute,
} as any)
const NurseDigitizeRoute = NurseDigitizeRouteImport.update({
  id: '/digitize',
  path: '/digitize',
  getParentRoute: () => NurseRoute,
} as any)
const NurseAppointmentsRoute = NurseAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ReceptionistProfilesPidRoute = ReceptionistProfilesPidRouteImport.update({
  id: '/profiles_/$pid',
  path: '/profiles/$pid',
  getParentRoute: () => ReceptionistRoute,
} as any)
const NursePatientRecordPidRoute = NursePatientRecordPidRouteImport.update({
  id: '/patient-record/$pid',
  path: '/patient-record/$pid',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorPatientRecordPidRoute = DoctorPatientRecordPidRouteImport.update({
  id: '/patient-record/$pid',
  path: '/patient-record/$pid',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clinic-signup': typeof ClinicSignupRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/nurse/appointments': typeof NurseAppointmentsRoute
  '/nurse/digitize': typeof NurseDigitizeRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/stock': typeof NurseStockRoute
  '/patient/alerts': typeof PatientAlertsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/medical-record': typeof PatientMedicalRecordRoute
  '/patient/privacy': typeof PatientPrivacyRoute
  '/pharmacist/analytics': typeof PharmacistAnalyticsRoute
  '/pharmacist/deliveries': typeof PharmacistDeliveriesRoute
  '/pharmacist/diagnostics': typeof PharmacistDiagnosticsRoute
  '/pharmacist/stock': typeof PharmacistStockRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/profiles': typeof ReceptionistProfilesRoute
  '/receptionist/queue': typeof ReceptionistQueueRoute
  '/receptionist/registration': typeof ReceptionistRegistrationRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/facilities': typeof SuperAdminFacilitiesRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacist/': typeof PharmacistIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/doctor/patient-record/$pid': typeof DoctorPatientRecordPidRoute
  '/nurse/patient-record/$pid': typeof NursePatientRecordPidRoute
  '/receptionist/profiles/$pid': typeof ReceptionistProfilesPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinic-signup': typeof ClinicSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/nurse/appointments': typeof NurseAppointmentsRoute
  '/nurse/digitize': typeof NurseDigitizeRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/stock': typeof NurseStockRoute
  '/patient/alerts': typeof PatientAlertsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/medical-record': typeof PatientMedicalRecordRoute
  '/patient/privacy': typeof PatientPrivacyRoute
  '/pharmacist/analytics': typeof PharmacistAnalyticsRoute
  '/pharmacist/deliveries': typeof PharmacistDeliveriesRoute
  '/pharmacist/diagnostics': typeof PharmacistDiagnosticsRoute
  '/pharmacist/stock': typeof PharmacistStockRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/profiles': typeof ReceptionistProfilesRoute
  '/receptionist/queue': typeof ReceptionistQueueRoute
  '/receptionist/registration': typeof ReceptionistRegistrationRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/facilities': typeof SuperAdminFacilitiesRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/patient': typeof PatientIndexRoute
  '/pharmacist': typeof PharmacistIndexRoute
  '/receptionist': typeof ReceptionistIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/doctor/patient-record/$pid': typeof DoctorPatientRecordPidRoute
  '/nurse/patient-record/$pid': typeof NursePatientRecordPidRoute
  '/receptionist/profiles/$pid': typeof ReceptionistProfilesPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clinic-signup': typeof ClinicSignupRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/nurse/appointments': typeof NurseAppointmentsRoute
  '/nurse/digitize': typeof NurseDigitizeRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/stock': typeof NurseStockRoute
  '/patient/alerts': typeof PatientAlertsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/medical-record': typeof PatientMedicalRecordRoute
  '/patient/privacy': typeof PatientPrivacyRoute
  '/pharmacist/analytics': typeof PharmacistAnalyticsRoute
  '/pharmacist/deliveries': typeof PharmacistDeliveriesRoute
  '/pharmacist/diagnostics': typeof PharmacistDiagnosticsRoute
  '/pharmacist/stock': typeof PharmacistStockRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/profiles': typeof ReceptionistProfilesRoute
  '/receptionist/queue': typeof ReceptionistQueueRoute
  '/receptionist/registration': typeof ReceptionistRegistrationRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/facilities': typeof SuperAdminFacilitiesRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacist/': typeof PharmacistIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/doctor/patient-record/$pid': typeof DoctorPatientRecordPidRoute
  '/nurse/patient-record/$pid': typeof NursePatientRecordPidRoute
  '/receptionist/profiles_/$pid': typeof ReceptionistProfilesPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clinic-signup'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacist'
    | '/receptionist'
    | '/signup'
    | '/super-admin'
    | '/two-factor'
    | '/admin/audit'
    | '/admin/staff'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/nurse/appointments'
    | '/nurse/digitize'
    | '/nurse/patients'
    | '/nurse/stock'
    | '/patient/alerts'
    | '/patient/appointments'
    | '/patient/medical-record'
    | '/patient/privacy'
    | '/pharmacist/analytics'
    | '/pharmacist/deliveries'
    | '/pharmacist/diagnostics'
    | '/pharmacist/stock'
    | '/receptionist/appointments'
    | '/receptionist/profiles'
    | '/receptionist/queue'
    | '/receptionist/registration'
    | '/super-admin/audit'
    | '/super-admin/facilities'
    | '/admin/'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
    | '/pharmacist/'
    | '/receptionist/'
    | '/super-admin/'
    | '/doctor/patient-record/$pid'
    | '/nurse/patient-record/$pid'
    | '/receptionist/profiles/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinic-signup'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/two-factor'
    | '/admin/audit'
    | '/admin/staff'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/nurse/appointments'
    | '/nurse/digitize'
    | '/nurse/patients'
    | '/nurse/stock'
    | '/patient/alerts'
    | '/patient/appointments'
    | '/patient/medical-record'
    | '/patient/privacy'
    | '/pharmacist/analytics'
    | '/pharmacist/deliveries'
    | '/pharmacist/diagnostics'
    | '/pharmacist/stock'
    | '/receptionist/appointments'
    | '/receptionist/profiles'
    | '/receptionist/queue'
    | '/receptionist/registration'
    | '/super-admin/audit'
    | '/super-admin/facilities'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/pharmacist'
    | '/receptionist'
    | '/super-admin'
    | '/doctor/patient-record/$pid'
    | '/nurse/patient-record/$pid'
    | '/receptionist/profiles/$pid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clinic-signup'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacist'
    | '/receptionist'
    | '/signup'
    | '/super-admin'
    | '/two-factor'
    | '/admin/audit'
    | '/admin/staff'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/nurse/appointments'
    | '/nurse/digitize'
    | '/nurse/patients'
    | '/nurse/stock'
    | '/patient/alerts'
    | '/patient/appointments'
    | '/patient/medical-record'
    | '/patient/privacy'
    | '/pharmacist/analytics'
    | '/pharmacist/deliveries'
    | '/pharmacist/diagnostics'
    | '/pharmacist/stock'
    | '/receptionist/appointments'
    | '/receptionist/profiles'
    | '/receptionist/queue'
    | '/receptionist/registration'
    | '/super-admin/audit'
    | '/super-admin/facilities'
    | '/admin/'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
    | '/pharmacist/'
    | '/receptionist/'
    | '/super-admin/'
    | '/doctor/patient-record/$pid'
    | '/nurse/patient-record/$pid'
    | '/receptionist/profiles_/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClinicSignupRoute: typeof ClinicSignupRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NurseRoute: typeof NurseRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  PharmacistRoute: typeof PharmacistRouteWithChildren
  ReceptionistRoute: typeof ReceptionistRouteWithChildren
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TwoFactorRoute: typeof TwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-signup': {
      id: '/clinic-signup'
      path: '/clinic-signup'
      fullPath: '/clinic-signup'
      preLoaderRoute: typeof ClinicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/receptionist/': {
      id: '/receptionist/'
      path: '/'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof ReceptionistIndexRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/pharmacist/': {
      id: '/pharmacist/'
      path: '/'
      fullPath: '/pharmacist/'
      preLoaderRoute: typeof PharmacistIndexRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super-admin/facilities': {
      id: '/super-admin/facilities'
      path: '/facilities'
      fullPath: '/super-admin/facilities'
      preLoaderRoute: typeof SuperAdminFacilitiesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/audit': {
      id: '/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminAuditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/receptionist/registration': {
      id: '/receptionist/registration'
      path: '/registration'
      fullPath: '/receptionist/registration'
      preLoaderRoute: typeof ReceptionistRegistrationRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/queue': {
      id: '/receptionist/queue'
      path: '/queue'
      fullPath: '/receptionist/queue'
      preLoaderRoute: typeof ReceptionistQueueRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/profiles': {
      id: '/receptionist/profiles'
      path: '/profiles'
      fullPath: '/receptionist/profiles'
      preLoaderRoute: typeof ReceptionistProfilesRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/appointments': {
      id: '/receptionist/appointments'
      path: '/appointments'
      fullPath: '/receptionist/appointments'
      preLoaderRoute: typeof ReceptionistAppointmentsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/pharmacist/stock': {
      id: '/pharmacist/stock'
      path: '/stock'
      fullPath: '/pharmacist/stock'
      preLoaderRoute: typeof PharmacistStockRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/pharmacist/diagnostics': {
      id: '/pharmacist/diagnostics'
      path: '/diagnostics'
      fullPath: '/pharmacist/diagnostics'
      preLoaderRoute: typeof PharmacistDiagnosticsRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/pharmacist/deliveries': {
      id: '/pharmacist/deliveries'
      path: '/deliveries'
      fullPath: '/pharmacist/deliveries'
      preLoaderRoute: typeof PharmacistDeliveriesRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/pharmacist/analytics': {
      id: '/pharmacist/analytics'
      path: '/analytics'
      fullPath: '/pharmacist/analytics'
      preLoaderRoute: typeof PharmacistAnalyticsRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/patient/privacy': {
      id: '/patient/privacy'
      path: '/privacy'
      fullPath: '/patient/privacy'
      preLoaderRoute: typeof PatientPrivacyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medical-record': {
      id: '/patient/medical-record'
      path: '/medical-record'
      fullPath: '/patient/medical-record'
      preLoaderRoute: typeof PatientMedicalRecordRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/alerts': {
      id: '/patient/alerts'
      path: '/alerts'
      fullPath: '/patient/alerts'
      preLoaderRoute: typeof PatientAlertsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/stock': {
      id: '/nurse/stock'
      path: '/stock'
      fullPath: '/nurse/stock'
      preLoaderRoute: typeof NurseStockRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/patients': {
      id: '/nurse/patients'
      path: '/patients'
      fullPath: '/nurse/patients'
      preLoaderRoute: typeof NursePatientsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/digitize': {
      id: '/nurse/digitize'
      path: '/digitize'
      fullPath: '/nurse/digitize'
      preLoaderRoute: typeof NurseDigitizeRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/appointments': {
      id: '/nurse/appointments'
      path: '/appointments'
      fullPath: '/nurse/appointments'
      preLoaderRoute: typeof NurseAppointmentsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/receptionist/profiles_/$pid': {
      id: '/receptionist/profiles_/$pid'
      path: '/profiles/$pid'
      fullPath: '/receptionist/profiles/$pid'
      preLoaderRoute: typeof ReceptionistProfilesPidRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/nurse/patient-record/$pid': {
      id: '/nurse/patient-record/$pid'
      path: '/patient-record/$pid'
      fullPath: '/nurse/patient-record/$pid'
      preLoaderRoute: typeof NursePatientRecordPidRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/patient-record/$pid': {
      id: '/doctor/patient-record/$pid'
      path: '/patient-record/$pid'
      fullPath: '/doctor/patient-record/$pid'
      preLoaderRoute: typeof DoctorPatientRecordPidRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientRecordPidRoute: typeof DoctorPatientRecordPidRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientRecordPidRoute: DoctorPatientRecordPidRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface NurseRouteChildren {
  NurseAppointmentsRoute: typeof NurseAppointmentsRoute
  NurseDigitizeRoute: typeof NurseDigitizeRoute
  NursePatientsRoute: typeof NursePatientsRoute
  NurseStockRoute: typeof NurseStockRoute
  NurseIndexRoute: typeof NurseIndexRoute
  NursePatientRecordPidRoute: typeof NursePatientRecordPidRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseAppointmentsRoute: NurseAppointmentsRoute,
  NurseDigitizeRoute: NurseDigitizeRoute,
  NursePatientsRoute: NursePatientsRoute,
  NurseStockRoute: NurseStockRoute,
  NurseIndexRoute: NurseIndexRoute,
  NursePatientRecordPidRoute: NursePatientRecordPidRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface PatientRouteChildren {
  PatientAlertsRoute: typeof PatientAlertsRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientMedicalRecordRoute: typeof PatientMedicalRecordRoute
  PatientPrivacyRoute: typeof PatientPrivacyRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAlertsRoute: PatientAlertsRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientMedicalRecordRoute: PatientMedicalRecordRoute,
  PatientPrivacyRoute: PatientPrivacyRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PharmacistRouteChildren {
  PharmacistAnalyticsRoute: typeof PharmacistAnalyticsRoute
  PharmacistDeliveriesRoute: typeof PharmacistDeliveriesRoute
  PharmacistDiagnosticsRoute: typeof PharmacistDiagnosticsRoute
  PharmacistStockRoute: typeof PharmacistStockRoute
  PharmacistIndexRoute: typeof PharmacistIndexRoute
}

const PharmacistRouteChildren: PharmacistRouteChildren = {
  PharmacistAnalyticsRoute: PharmacistAnalyticsRoute,
  PharmacistDeliveriesRoute: PharmacistDeliveriesRoute,
  PharmacistDiagnosticsRoute: PharmacistDiagnosticsRoute,
  PharmacistStockRoute: PharmacistStockRoute,
  PharmacistIndexRoute: PharmacistIndexRoute,
}

const PharmacistRouteWithChildren = PharmacistRoute._addFileChildren(
  PharmacistRouteChildren,
)

interface ReceptionistRouteChildren {
  ReceptionistAppointmentsRoute: typeof ReceptionistAppointmentsRoute
  ReceptionistProfilesRoute: typeof ReceptionistProfilesRoute
  ReceptionistQueueRoute: typeof ReceptionistQueueRoute
  ReceptionistRegistrationRoute: typeof ReceptionistRegistrationRoute
  ReceptionistIndexRoute: typeof ReceptionistIndexRoute
  ReceptionistProfilesPidRoute: typeof ReceptionistProfilesPidRoute
}

const ReceptionistRouteChildren: ReceptionistRouteChildren = {
  ReceptionistAppointmentsRoute: ReceptionistAppointmentsRoute,
  ReceptionistProfilesRoute: ReceptionistProfilesRoute,
  ReceptionistQueueRoute: ReceptionistQueueRoute,
  ReceptionistRegistrationRoute: ReceptionistRegistrationRoute,
  ReceptionistIndexRoute: ReceptionistIndexRoute,
  ReceptionistProfilesPidRoute: ReceptionistProfilesPidRoute,
}

const ReceptionistRouteWithChildren = ReceptionistRoute._addFileChildren(
  ReceptionistRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminAuditRoute: typeof SuperAdminAuditRoute
  SuperAdminFacilitiesRoute: typeof SuperAdminFacilitiesRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAuditRoute: SuperAdminAuditRoute,
  SuperAdminFacilitiesRoute: SuperAdminFacilitiesRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClinicSignupRoute: ClinicSignupRoute,
  DoctorRoute: DoctorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NurseRoute: NurseRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  PharmacistRoute: PharmacistRouteWithChildren,
  ReceptionistRoute: ReceptionistRouteWithChildren,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TwoFactorRoute: TwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
